ALTER TABLE plugins DROP COLUMN error;
ALTER TABLE plugins ADD COLUMN error TEXT;

ALTER TABLE plugins ADD COLUMN testok BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE plugins ADD COLUMN vetok BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE plugins ADD COLUMN compileok BOOLEAN DEFAULT FALSE NOT NULL;
