CREATE TABLE users (
	id SERIAL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE sessions (
	token VARCHAR(255) NOT NULL,
	userid INTEGER NOT NULL,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE csrfs (
	token VARCHAR(255) NOT NULL,
	userid INTEGER NOT NULL,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (userid)
);
CREATE TABLE plugins (
	id SERIAL,
	name VARCHAR(255), 
	path VARCHAR(255) UNIQUE NOT NULL,
	description TEXT,
	downloadcount INTEGER DEFAULT 0 NOT NULL,
	userid INTEGER NOT NULL,
	compileok BOOLEAN DEFAULT FALSE NOT NULL,
	vetok BOOLEAN DEFAULT FALSE NOT NULL,
	testok BOOLEAN DEFAULT FALSE NOT NULL,
	error TEXT,
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);
-- CREATE UNIQUE INDEX plugins_name_idx ON plugins (name) WHERE name IS NOT NULL;
ALTER TABLE plugins ADD CONSTRAINT plugins_name_idx UNIQUE (name);
CREATE EXTENSION pg_trgm;
CREATE INDEX plugins_trgm_idx ON plugins USING gin (
	name gin_trgm_ops,
	description gin_trgm_ops
);
