ALTER TABLE plugins DROP COLUMN compileok;
ALTER TABLE plugins DROP COLUMN vetok;
ALTER TABLE plugins DROP COLUMN testok;

ALTER TABLE plugins DROP COLUMN error;
ALTER TABLE plugins ADD COLUMN error BOOLEAN DEFAULT FALSE NOT NULL;
